linters-settings:
  cyclop:
    max-complexity: 12
  gocognit:
    min-complexity: 12
  gocyclo:
    min-complexity: 12
  lll:
    line-length: 120
  funlen:
    lines: 80
    statements: 50
  dupl:
    threshold: 150
  revive:
    severity: warning
    confidence: 0.8
  depguard:
    list-type: deny
    include-go-root: false
    packages:
      - github.com/pkg/errors
    packages-with-error-message:
      github.com/pkg/errors: "Use the standard 'errors' package or Go 1.13+ error wrapping instead."
  errcheck:
    check-type-assertions: true
    check-blank: true

linters:
  enable:
    # Core correctness & safety
    - govet
    - staticcheck
    - typecheck
    - unused
    - errcheck
    - errorlint
    - ineffassign
    - contextcheck

    # Style & consistency
    - gofmt
    - goimports
    - misspell
    - stylecheck
    - revive
    # - lll
    - bodyclose

    # Complexity & structure
    - cyclop
    - gocognit
    - gocyclo
    # - funlen
    - dupl
    - nestif

    # Modernization & best practices
    - gosimple
    - prealloc
    - unparam
    - nilerr
    - makezero

    # Concurrency / loop safety
    - copyloopvar
    - tenv

presets:
  - bugs
  - error
  - performance
  - style
  - unused

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - generated
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - dupl
      text: "is duplicated"
    - linters:
        - lll
      text: "line is too long"
  exclude-files:
    - generated.go

output:
  formats:
    - format: colored-line-number
  sort-results: true
  print-issued-lines: true
  uniq-by-line: true
  color: auto
  severity: false
  issues-exit-code: 1
  max-issues-per-linter: 0
  max-same-issues: 0

fast: false
