version: "2"
run:
  tests: true
  external:
    - path: nilaway
      args:
        - -include-pkgs=./...
        - ./...
linters:
  enable:
    - misspell
    - revive
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 3
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
